name: Cypress Tests

on: [push]

jobs:
  cypress:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Configure Node Version
        uses: actions/setup-node@v1
        with:
            node-version: 12

      - name: Update npm
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          command: npm run cy:run
          # start: npm start