name: Cypress Tests

on: [push]

jobs:
  cypress:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          config-file: cypress/config/cypress.imp.json
          spec: cypress/integration/Test/*.js

        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          CYPRESS_se_login: ${{secrets.CYPRESS_SE_LOGIN}}
          CYPRESS_se_password: ${{secrets.CYPRESS_SE_PASSWORD}}
          CYPRESS_se_imp_aca_cookie: ${{secrets.CYPRESS_SE_IMP_ACA_COOKIE}}